### ISSUE TITLE
New update broke the extension (kinda)

### ISSUE THREAD

**Issue by shahin365** [luiserdef/twitter-real-verified#10]
Hi, the extension had only one job and did it flawlessly. show $ instead of a checkmark in the badge for twitter blue, and it worked. since yesterday's update and added new option to change the badge color, it seems it has to load the page to change the color so some of the checkmark colors change while some of them don't and it's annoying. https://i.imgur.com/GdiXRa9.png
I changed the color to blue but it won't save my change and it switches back to #2C85AD. Can you please keep it simple and revert it back to the previous version? if it ain't broke, don't fix it.

**Comment by luiserdef** [comment]
Hi, thanks for letting me know about the problem and I'm sorry to hear that.
I think you're using Firefox if that's correct, it would help if you could tell me which version you're using (if possible).
One thing to remember is that you need to be on the twitter page for the changes to be saved and work on twitter.
Even so, if you still prefer the previous version, you can find it in the release section (this repository) if you want and then you can install it.

**Comment by shahin365** [comment]
> Hi, thanks for letting me know about the problem and I'm sorry to hear that. I think you're using Firefox if that's correct, it would help if you could tell me which version you're using (if possible). One thing to remember is that you need to be on the twitter page for the changes to be saved and work on twitter. Even so, if you still prefer the previous version, you can find it in the release section (this repository) if you want and then you can install it.

seems like you fixed it on 1.1.1 update. thank you.
