### ISSUE TITLE
Set up the icon

### ISSUE THREAD

**Issue by MyNameIsTroll** [luiserdef/twitter-real-verified#2]
Hello.
I really like your browser extension, thank you for doing it.
Unfortunately I think the little dollar icon is not very readable. I wondered if it would be possible to change it or let the user set it. For example, choosing an emoji or changing its color or opacity.

**Comment by luiserdef** [comment]
Hello, Sorry for not answering.
I just added a functionality that may help and it will be available soon.
Thanks for the observation.

**Comment by MyNameIsTroll** [comment]
wow, this is great! Thanks ^_<
