### ISSUE TITLE
Inconsistency in where the dollar sign is displayed

### ISSUE THREAD

**Issue by cooljeanius** [luiserdef/twitter-real-verified#26]
**Describe the bug**
Sometimes an account will get a dollar symbol in some places, but the regular blue check in others

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to an account that is both legacy-verified and subscribes to Twitter Blue
2. Try to reply one of their tweets
3. Note that the dollar sign displays in the reply window, but not by their profile
4. Repeat with other similar situations such as Twitter Spaces, etc.

**Expected behavior**
Some sort of consistency

**Screenshots**
<img width="902" alt="Screen Shot 2023-06-09 at 02 54 32" src="https://github.com/luiserdef/twitter-real-verified/assets/1388660/da578a69-f25d-41d8-936f-95f4feb480be">
(arrows added)

**Desktop (please complete the following information):**
 - Firefox
 - 113.0.2

**Comment by luiserdef** [comment]
Hi. Thanks for letting me know about this issue. I will check it.
