### ISSUE TITLE
Bug with options window

### ISSUE THREAD

**Issue by Melvyn0** [luiserdef/twitter-real-verified#30]
**Describe the bug**
Hey, your extension is very good and works great but, when I click on the extension to access the options, the menu that comes up is tiny. Like, a rectangle, a few pixels by a few pixels, so I can't edit anything (see screenshot joined).

**Expected behavior**
I just expected the extension's options window to open properly, without being a few pixel rectangle.

**Screenshots**
![image](https://github.com/luiserdef/twitter-real-verified/assets/61357269/78c1b6db-4575-47bf-8fd6-33f72a4d701c)

**Desktop (please complete the following information):**
- OS version : Windows 11 
- Browser : Chrome Dev version : 116.0.5845.14 (Official build) dev (64 bits)
- Version of extension : 2.1.5

**Comment by luiserdef** [comment]
Hi!
Thanks for letting me know about this bug.
I'll take a look to find out what's going on
