### ISSUE TITLE
Handle users who hide their checkmark

### ISSUE THREAD

**Issue by cooljeanius** [luiserdef/twitter-real-verified#31]
Twitter Blue users are going to be able to hide their checkmarks soon: https://twitter.com/PopBase/status/1686609762602172416
I'm thinking maybe introducing a 3rd type of checkmark for the hidden ones would help distinguish it? Say, a clear one with a dotted line for an outline, or a semi-transparent one, or something...

**Comment by luiserdef** [comment]
Hi! thanks for letting me know about this. I will think about that.

**Comment by cooljeanius** [comment]
> Twitter Blue users are going to be able to hide their checkmarks soon: [twitter.com/PopBase/status/1686609762602172416](https://twitter.com/PopBase/status/1686609762602172416)

Archive link, in case it disappears: http://web.archive.org/web/20230805055318/https://twitter.com/PopBase/status/1686609762602172416

**Comment by cooljeanius** [comment]
...actually never mind, it looks like this feature will be going away again:
https://www.theverge.com/2024/4/11/24127906/x-premium-users-can-no-longer-hide-their-blue-checks
