### ISSUE TITLE
Version 2.1.6 is not in the Edge Add-ons site

### ISSUE THREAD

**Issue by jmoralesv** [luiserdef/twitter-real-verified#32]
**Describe the bug**
Version 2.1.6 is not in the Edge Add-ons site; version 2.1.5 is present instead. As a result, after installing the extension, when clicking on the icon of the extension in Microsoft Edge, the window is too narrow.

**To Reproduce**
1. Go to the Microsoft Edge Add-ons site and look for the [Twitter Real Verified extension](https://microsoftedge.microsoft.com/addons/detail/twitter-real-verified/llkfeengcmnpbpcgmchgjcjmfoekedij)
3. Check the version and updated date in the right-hand side section
![image](https://github.com/luiserdef/twitter-real-verified/assets/2235876/37b17998-5d5b-411c-a055-a790338fa089)
5. Install the extension
6. Go to Twitter
7. Click on the extension icon
8. Notice the width of the extension, it's to narrow
![image](https://github.com/luiserdef/twitter-real-verified/assets/2235876/5b914bec-07ce-4e75-8542-7046a328c0b3)

**Expected behavior**
Version 2.1.6 should be present in the Microsoft Edge Add-ons site, as this version solves this issue.

**Desktop (please complete the following information):**
 - Microsoft Edge in Windows 11
 - Version 116.0.1938.62

**Comment by luiserdef** [comment]
Hi!
I uploaded the version to Edge, It will be available in a few hours.

**Comment by jmoralesv** [comment]
Hi @luiserdef is there any update on this one? I can still see version 2.1.5 offered in the Microsoft Edge's Add-ons site. Maybe Microsoft takes more time than expected on updating extensions?

**Comment by luiserdef** [comment]
> Hi @luiserdef is there any update on this one? I can still see version 2.1.5 offered in the Microsoft Edge's Add-ons site. Maybe Microsoft takes more time than expected on updating extensions?

Hi, yes.
I had problems uploading version 2.1.6 to edge since they rejected the extension, problems related to the product itself (name, icons, etc.) despite making the adjustments I kept rejecting. In any case, remember that you can download the extension also from the chrome store, which is also compatible with edge. 
Maybe it is not the answer you were looking for but at least it has a solution by downloading it from the chrome store.

**Comment by jmoralesv** [comment]
Hi @luiserdef it's fine, yes, Edge supports Chrome extensions and that's a valid workaround. It's a shame that Microsoft is not accepting the updated version.

If you agree, I can close this issue.
