### ISSUE TITLE
Domain change to x.com makes extension not work

### ISSUE THREAD

**Issue by Hans5958** [luiserdef/twitter-real-verified#63]
**Describe the bug**
A change has been made so twitter.com has been moved to x.com and twitter.com now redirects to x.com, making this extension not work at all due to the host permissions being set on twitter.com.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Go to https://x.com
2. Observe behavior of extension not running on the website

**Expected behavior**
Extension should've at least running on the site.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Mozilla Firefox 127.0b2
 - Twitter Real Verified 2.1.7

**Additional context**
There are some other changes that makes the extension doesn't work anymore, even before the domain change, but I may not be able to reproduce the error clearly due to this domain change.

**Comment by MasterDirector99** [comment]
It happened on Google Chrome too!

**Comment by cooljeanius** [comment]
> Thanks for reporting! I made a new update. It will be available soon in chrome and Firefox.

Could you put it under the Releases tab, too?

**Comment by luiserdef** [comment]
> > Thanks for reporting! I made a new update. It will be available soon in chrome and Firefox.
> 
> Could you put it under the Releases tab, too?

I had placed it as a pre-release but, yes.

**Comment by MasterDirector99** [comment]
Just made a little concept about it.
(had to use inspect editor.)
![Screenshot 2024-05-20 215413](https://github.com/luiserdef/twitter-real-verified/assets/74268152/c6067cce-7a26-4846-a071-2c7914af283a)

**Comment by luiserdef** [comment]
New update v2.1.8 is now available in chrome and Firefox.
